name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build-dir:
          - aad-user-sync
          - create-teams-from-directories
          - sync-repositories
          - sync-users
    defaults:
      run:
        working-directory: "${{ matrix.build-dir }}"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: install vercel/ncc
        run: npm i -g @vercel/ncc

      - name: Build dist
        run: npm run build

      # tar all of dist so when we try to extract it, we dont need to move files around
      - name: tar dir
        run: tar cvzf dist.tar dist

      - name: upload-artifacts
        uses: actions/upload-artifact@v3
        with:
          name: "${{ matrix.build-dir }}"
          path: "${{ matrix.build-dir }}/dist.tar"
          retention-days: 5

  pushback:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Download artifacts
        uses: actions/download-artifact@v3
      - name: move files
        run: |
          base_dir=$PWD
          for dir in */; do
            #prettier-ignore
            cd $dir
            tar xvzf dist.tar
            rm -f dist.tar
            cd $base_dir
          done
      - name: Check status
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git status
