name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build-dir:
          - aad-user-sync
          - create-teams-from-directories
          - sync-repositories
          - sync-users
    defaults:
      run:
        working-directory: "${{ matrix.build-dir }}"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build dist
        run: npm run build

      - name: upload-artifacts
        uses: actions/upload-artifact@v3
        with:
          name: "${{ matrix.build-dir }}"
          path: dist/
          retention-days: 5

  pushback:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Download artifacts
        uses: actions/download-artifact@v3
      - name: Check status
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git status
