name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version number"
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.version }}
          release_name: Release ${{ github.event.inputs.version }}
          body: |
            This is the release notes for version ${{ github.event.inputs.version }}.
          draft: false
          prerelease: false
